---
name: 'Test PR'
on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches: 
      - 'master'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  esdt-test:
    name: ESDT Test
    runs-on: [ self-hosted, linux, flyweight ]
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3
      - name: Run Tests
        run: |
          make test

  esdt-test-prove:
    name: ESDT Prove 
    runs-on: [ self-hosted, linux, normal ]
    steps:
      - name: Run Prove
        uses: actions/checkout@v3
      - name: Run Prove
        run: |
          make test-prove
